### ISSUE TITLE
calendar.history erroneously claims pandas were discovered in 1927

### ISSUE THREAD

**Issue by fpdotmonkey** [MirBSD/calendar#1]
`calendar.history:424` reads

```
11/09	Giant panda discovered (?!), China, 1927
```

I'm wondering if there's a citation for this?  It seem a bit unbelievable that people and pandas would've coexisted nearby to each other for thousands of years without ever coming into contact.  Indeed, to the extent that it can be trusted, [Wikipedia](https://en.wikipedia.org/wiki/Giant_panda#Early_references) claims that a 1st century BCE Chinese empress was buried with a panda skull.  1927 does seem like around the time that there was a *European* discovery of pandas, but I don't see that particular date corroborated anywhere.  As well, European discovery of pandas should not be conflated with general discovery of the animal.

**Comment by mirabilos** [comment]
Sorry I only get to this now; I’ve only seen this today by accident, I never got a notification about this issue.

I personally read this as “someone said they saw a giant panda once”, i.e. not as pandas in general were discovered, but one sized suitably differently enough to be noted.

Upstream for this file is <http://cvsweb.openbsd.org/src/usr.bin/calendar/calendars/calendar.history?rev=HEAD> and they also still have it. You might wish to raise an issue there and ask where they get this information from… but it may very well date back to UCB CSRG times.

**Comment by fpdotmonkey** [comment]
Thanks, I reported to upstream and they will/have removed the line.
